bevy_input_focus: don't add nothing when no input is enabled (#22293)
# Objective

- `cargo build --no-default-features --features bevy_input_focus` fails:
```
   Compiling bevy_input_focus v0.18.0-dev (/home/runner/work/bevy-releasability/bevy-releasability/crates/bevy_input_focus)
error[E0599]: no method named `in_set` found for unit type `()` in the current scope
   --> crates/bevy_input_focus/src/lib.rs:236:22
    |
228 | /                 (
229 | |                     #[cfg(feature = "keyboard")]
230 | |                     dispatch_focused_input::<KeyboardInput>,
231 | |                     #[cfg(feature = "gamepad")]
...   |
236 | |                     .in_set(InputFocusSystems::Dispatch),
    | |_____________________-^^^^^^
    |
```
- Introduced in #22177

## Solution

- Don't add an empty system tuple when no input feature is enabled