bevy_asset fails lint expectation in wasm on ProcessError (#22181)
# Objective

- `cargo clippy --target wasm32-unknown-unknown -p bevy_asset --no-deps
-- -D warnings` fails with
```
error: this lint expectation is unfulfilled
   --> crates/bevy_asset/src/processor/process.rs:235:9
    |
235 |         clippy::result_large_err,
    |         ^^^^^^^^^^^^^^^^^^^^^^^^
    |
```

## Solution

- don't expect the lint in wasm